sudo: required
language: node_js
node_js:
- 8
before_install:
  # Script credits @spookyUnknownUser https://gist.github.com/spookyUnknownUser/dd8c75319ec581c1028310cedaea786c
  - export static_host=https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - export filename=ffmpeg-git-64bit-static.tar.xz
  - cd /usr/local/bin
  - sudo mkdir ffmpeg
  - echo "Made dir"
  - cd ffmpeg
  - echo "Downloading"
  - sudo wget $static_host
  - echo "Download finished"
  - echo "Unzipping"
  - sudo tar xf $filename --strip-components=1
  - sudo rm $filename
  - echo "Symlinking"
  - ln -s /usr/local/bin/ffmpeg/ffmpeg /usr/bin/ffmpeg
  - ln -s /usr/local/bin/ffmpeg/ffpropbe /usr/bin/ffpropbe
  - echo "FFmpeg installed!"
install:
  - npm install